server:
  port: 8080
  servlet:
    contextPath: /blog
spring:
  application:
    name: blog-service
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: validate
      #jdbc.lob.non_contextual_creation: true
    generate-ddl: false
    open-in-view: false
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/blogs
    driverClassName: org.postgresql.Driver
logging:
  level:
    org.hibernate.SQL: ERROR
    org.springframework.data: DEBUG
  file:
    name: logs/blogging-service.log