server:
  port: 8080
  servlet:
    contextPath: /blog
spring:
  application:
    name: blog-service
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      #jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    open-in-view: false
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/blogs
    driverClassName: org.postgresql.Driver
logging:
  level:
    org.hibernate.SQL: ERROR
    org.springframework.data: DEBUG
  file:
    name: logs/blogging-service.log